//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Programming_Class_III.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Incident
    {
        [DisplayName("Incident ID")]
        public int IncidentID { get; set; }

        [DisplayName("Customer ID")]
        public int CustomerID { get; set; }

        [DisplayName("Product Code")]
        public string ProductCode { get; set; }

        [DisplayName("Technician ID")]
        public Nullable<int> TechID { get; set; }

        [DisplayName("Date Opened")]
        public System.DateTime DateOpened { get; set; }

        [DisplayName("Date Closed")]
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string Title { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Technician Technician { get; set; }
    }
}
