//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Programming_Class_III.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Registration
    {
        [DisplayName("Customer ID")]    
        public int CustomerID { get; set; }

        [DisplayName("Product Code")]
        public string ProductCode { get; set; }

        [DisplayName("Registration Date")]
        public System.DateTime RegistrationDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
