//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Programming_Class_III.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class State
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public State()
        {
            this.Customers = new HashSet<Customer>();
        }
        
        [DisplayName ("State Code")]
        public string StateCode { get; set; }

        [DisplayName("State Name")]
        public string StateName { get; set; }

        [DisplayName("First Zip Code")]
        public int FirstZipCode { get; set; }

        [DisplayName("Last Zip Code")]
        public int LastZipCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
